// SX Fund — core pool constants from POP
export const POOL = {
  name: "SX Fund",
  nav: 262_500,
  navCurrency: "USDC",
  underlying: 350_000,
  underlyingCurrency: "EUR",
  blendedYieldMin: 9,
  blendedYieldMax: 12,
  ltv: 75,
  network: "Polygon",
  poolAddress: "0x7C3AED...f4B2",
  centrifugePool: "SX-POOL-01",
};

export const TRANCHES = [
  {
    id: "DROP",
    name: "DROP",
    label: "Senior",
    allocation: 70,
    yieldMin: 6,
    yieldMax: 8,
    tvl: 183_750,
    color: "emerald" as const,
    colorClass: "text-emerald-400",
    bgClass: "bg-emerald-400/10 border-emerald-400/20",
    badgeClass: "bg-emerald-400/15 text-emerald-400",
    priority: "Highest",
    description: "Senior protected tranche — first in, last out.",
  },
  {
    id: "MEZZ",
    name: "MEZZ",
    label: "Mezzanine",
    allocation: 10,
    yieldMin: 10,
    yieldMax: 12,
    tvl: 26_250,
    color: "amber" as const,
    colorClass: "text-amber-400",
    bgClass: "bg-amber-400/10 border-amber-400/20",
    badgeClass: "bg-amber-400/15 text-amber-400",
    priority: "Medium",
    description: "Mezzanine buffer — absorbs losses above TIN.",
  },
  {
    id: "TIN",
    name: "TIN",
    label: "Junior",
    allocation: 20,
    yieldMin: 15,
    yieldMax: 18,
    tvl: 52_500,
    color: "rose" as const,
    colorClass: "text-rose-400",
    bgClass: "bg-rose-400/10 border-rose-400/20",
    badgeClass: "bg-rose-400/15 text-rose-400",
    priority: "First Loss",
    description: "Junior equity tranche — highest risk, highest yield.",
  },
];

export const WATERFALL_STEPS = [
  { id: 1, label: "Protocol Fees",  amount: 1_312,  cumulative: 1_312,  color: "#6366f1" },
  { id: 2, label: "DROP Principal", amount: 183_750, cumulative: 185_062, color: "#10b981" },
  { id: 3, label: "DROP Yield",     amount: 10_500,  cumulative: 195_562, color: "#34d399" },
  { id: 4, label: "MEZZ Principal", amount: 26_250,  cumulative: 221_812, color: "#f59e0b" },
  { id: 5, label: "MEZZ Yield",     amount: 2_888,   cumulative: 224_700, color: "#fbbf24" },
  { id: 6, label: "TIN Principal",  amount: 52_500,  cumulative: 277_200, color: "#f43f5e" },
  { id: 7, label: "TIN Yield",      amount: 8_400,   cumulative: 285_600, color: "#fb7185" },
  { id: 8, label: "Excess",         amount: 0,       cumulative: 285_600, color: "#7c3aed" },
];

export const ORACLE_CHECKPOINTS = [
  { id: 1, label: "Loan Originated",    description: "Smart contract deployed, loan funded on-chain", icon: "origin" },
  { id: 2, label: "Loading Confirmed",  description: "Goods loaded at origin, CMR issued", icon: "load" },
  { id: 3, label: "Border Crossing",    description: "Customs cleared, cross-border transit initiated", icon: "border" },
  { id: 4, label: "Delivery Confirmed", description: "Warehouse receipt signed by consignee", icon: "delivery" },
  { id: 5, label: "Payment Received",   description: "Buyer payment settled to SPV account", icon: "payment" },
  { id: 6, label: "Loan Repaid",        description: "Principal + yield repaid to pool, NFT burned", icon: "repaid" },
];

// IPFS gateway base — all documents pinned on Pinata
const IPFS = "https://gateway.pinata.cloud/ipfs";

// Root manifest CID (full JSON index of all 10 deals)
export const IPFS_MANIFEST_CID = "QmeghB6yMHHznFp6tBW7cLTeLAsHrNLo6sFkPXnMKRMsvS";

// Root-level documents (deal overview xlsx + debt calendar pdf)
export const ROOT_DOCS = {
  dealSummary: {
    name: "Information regarding each deal.xlsx",
    cid: "QmYDpi8JjVyJiQUaedqAmwtgA2gFsgX8HJc3fBy7d6oNAY",
    url: `${IPFS}/QmYDpi8JjVyJiQUaedqAmwtgA2gFsgX8HJc3fBy7d6oNAY`,
  },
  debtCalendar: {
    name: "Календар заборгованості.pdf",
    cid: "Qme1jjDKaEk863TWHewHQMGmF3hETMPCWzRMMTqcrLhtJR",
    url: `${IPFS}/Qme1jjDKaEk863TWHewHQMGmF3hETMPCWzRMMTqcrLhtJR`,
  },
};

// On-chain infrastructure (public addresses only — no API keys, no server IPs)
export const INFRASTRUCTURE = {
  network: "Polygon",
  serverWallet: "0x7feEa1A1aB35E8fAFe71f473269C68951f0DB793",
  smartWallet: "0x83309B8c28B9DbC6386F0C68962D00B33A0bd80c",
  safeAddress: "TBD — 2-of-3 multisig",
  // gcpVM IP removed — never store server IPs in client code
};

// Real FG Geniivske trade contracts — OSKUTUOTE OY (FI) → CEREAL CROPS TRADING LLP (UK) → FG GENIIVSKE (UA)
export const DEALS = [
  {
    id: "RWA-SX-001",
    contractRef: "IT-211025",
    name: "Striped Sunflower Seeds — 22 MT",
    type: "Trade Receivable",
    assetType: "trade_receivable" as const,
    commodity: "Striped Sunflower Seeds",
    volumeMT: 22,
    buyer: "OSKUTUOTE OY",
    buyerCountry: "Finland",
    intermediary: "CEREAL CROPS TRADING LLP",
    loanAmount: 16_500,
    contractValue: 22_000,
    currency: "USDC",
    tenor: "30 days",
    tenorDays: 30,
    aprMin: 6,
    aprMax: 8,
    ltv: 75,
    stage: "Repaid" as const,
    status: "matured" as const,
    tranche: "DROP",
    oracleCompleted: 6,
    oracleTotal: 6,
    counterparty: "FG GENIIVSKE",
    originator: "SX Capital",
    originationDate: "2025-10-21",
    maturityDate: "2025-11-20",
    metadataCid: "QmaESvxU1EGktVrDGyDcYZxF6Wz2fRomtH3JLNkEPaGHQf",
    ipfsDocuments: [
      { label: "Contract",             name: "CONTRACT.pdf",                         cid: "QmY8eDu2bsQPYSy5eKbxUPaEHjtpn1LYzAuNRjTjuhAN5U", url: `${IPFS}/QmY8eDu2bsQPYSy5eKbxUPaEHjtpn1LYzAuNRjTjuhAN5U` },
      { label: "Declaration / CMR / EUR.1 / Phyto", name: "declaration_CMR_invoice_EUR1_Phyto.pdf", cid: "QmcD7JaHYpMwua2g4smbP8NoXnqNrJm6XKM6nqziiCMsuG", url: `${IPFS}/QmcD7JaHYpMwua2g4smbP8NoXnqNrJm6XKM6nqziiCMsuG` },
      { label: "Invoice",              name: "INVOICE-110102025.pdf",                cid: "QmaxCmba7BQeJqEzYyCxwxdrn93RvJmcuBAs29Qs3PeeXq", url: `${IPFS}/QmaxCmba7BQeJqEzYyCxwxdrn93RvJmcuBAs29Qs3PeeXq` },
      { label: "T-1 Transit Doc",      name: "T-1_inv_110102025.pdf",               cid: "Qmeph7MnipoWGDnZGEEssCjqDZ62CUbtqtiHzpxch8AnBW", url: `${IPFS}/Qmeph7MnipoWGDnZGEEssCjqDZ62CUbtqtiHzpxch8AnBW` },
    ],
    checkpoints: [
      { id: 1, status: "completed" as const, txHash: "0xabc001...", date: "2025-10-21" },
      { id: 2, status: "completed" as const, txHash: "0xabc002...", date: "2025-10-22" },
      { id: 3, status: "completed" as const, txHash: "0xabc003...", date: "2025-10-24" },
      { id: 4, status: "completed" as const, txHash: "0xabc004...", date: "2025-10-28" },
      { id: 5, status: "completed" as const, txHash: "0xabc005...", date: "2025-11-10" },
      { id: 6, status: "completed" as const, txHash: "0xabc006...", date: "2025-11-20" },
    ],
  },
  {
    id: "RWA-SX-002",
    contractRef: "IT-241025",
    name: "Striped Sunflower Seeds — 22 MT",
    type: "Trade Receivable",
    assetType: "trade_receivable" as const,
    commodity: "Striped Sunflower Seeds",
    volumeMT: 22,
    buyer: "OSKUTUOTE OY",
    buyerCountry: "Finland",
    intermediary: "CEREAL CROPS TRADING LLP",
    loanAmount: 16_500,
    contractValue: 22_000,
    currency: "USDC",
    tenor: "30 days",
    tenorDays: 30,
    aprMin: 6,
    aprMax: 8,
    ltv: 75,
    stage: "Repaid" as const,
    status: "matured" as const,
    tranche: "DROP",
    oracleCompleted: 6,
    oracleTotal: 6,
    counterparty: "FG GENIIVSKE",
    originator: "SX Capital",
    originationDate: "2025-10-24",
    maturityDate: "2025-11-23",
    metadataCid: "QmdDFciBW8GcRcSccZhwcAH4pG3Ph68UA4MPwmCZjTzMnQ",
    ipfsDocuments: [
      { label: "Contract",             name: "CONTRACT.pdf",                         cid: "QmUr6p3kqPx9kz8d6zKwLXcey1NhjyetCCuBmwwFah97aU", url: `${IPFS}/QmUr6p3kqPx9kz8d6zKwLXcey1NhjyetCCuBmwwFah97aU` },
      { label: "Declaration / CMR / EUR.1 / Phyto", name: "declaration_CMR_invoice_EUR1_Phyto.pdf", cid: "QmeajqCtZnxt5f7rvG6hPQYnqVKJbH6zqqBXCt83EGoUpF", url: `${IPFS}/QmeajqCtZnxt5f7rvG6hPQYnqVKJbH6zqqBXCt83EGoUpF` },
      { label: "Invoice",              name: "INVOICE-113102025.pdf",                cid: "QmW5R2MVPwiRdFLNndnMYJjre7gDru2j9jwV5PozoNY7F7", url: `${IPFS}/QmW5R2MVPwiRdFLNndnMYJjre7gDru2j9jwV5PozoNY7F7` },
      { label: "T-1 Transit Doc",      name: "T-1_inv_113102025.pdf",               cid: "QmScVtyu2MWAwYQL7TCa2t27thC4dG8N2rrkdKwJ74Hp1B", url: `${IPFS}/QmScVtyu2MWAwYQL7TCa2t27thC4dG8N2rrkdKwJ74Hp1B` },
    ],
    checkpoints: [
      { id: 1, status: "completed" as const, txHash: "0xbcd001...", date: "2025-10-24" },
      { id: 2, status: "completed" as const, txHash: "0xbcd002...", date: "2025-10-25" },
      { id: 3, status: "completed" as const, txHash: "0xbcd003...", date: "2025-10-27" },
      { id: 4, status: "completed" as const, txHash: "0xbcd004...", date: "2025-10-31" },
      { id: 5, status: "completed" as const, txHash: "0xbcd005...", date: "2025-11-12" },
      { id: 6, status: "completed" as const, txHash: "0xbcd006...", date: "2025-11-23" },
    ],
  },
  {
    id: "RWA-SX-003",
    contractRef: "IT-271025",
    name: "Striped Sunflower Seeds — 23 MT + Kernel 391 MT",
    type: "Trade Receivable",
    assetType: "trade_receivable" as const,
    commodity: "Striped Sunflower Seeds + Sunflower Kernel",
    volumeMT: 23,
    buyer: "OSKUTUOTE OY",
    buyerCountry: "Finland",
    intermediary: "CEREAL CROPS TRADING LLP",
    loanAmount: 17_250,
    contractValue: 23_000,
    currency: "USDC",
    tenor: "30 days",
    tenorDays: 30,
    aprMin: 6,
    aprMax: 8,
    ltv: 75,
    stage: "Repaid" as const,
    status: "matured" as const,
    tranche: "DROP",
    oracleCompleted: 6,
    oracleTotal: 6,
    counterparty: "FG GENIIVSKE",
    originator: "SX Capital",
    originationDate: "2025-10-27",
    maturityDate: "2025-11-26",
    metadataCid: "QmP7AaLm9EGjKU4dWRzqGNkymopBFaNAQa23x13QYVdQvr",
    ipfsDocuments: [
      { label: "Contract",             name: "CONTRACT.pdf",                         cid: "QmSSsoUE7hTaVreq61mZCeSANpZTbvtKu4fmpcDaf7wBUJ", url: `${IPFS}/QmSSsoUE7hTaVreq61mZCeSANpZTbvtKu4fmpcDaf7wBUJ` },
      { label: "Declaration / CMR / EUR.1 / Phyto", name: "declaration_CMR_invoice_EUR1_Phyto.pdf", cid: "QmbyYbx6qi9GKbLFdzoYMs7NABK4piQ46KanM8vUn7q4G6", url: `${IPFS}/QmbyYbx6qi9GKbLFdzoYMs7NABK4piQ46KanM8vUn7q4G6` },
      { label: "Invoice",              name: "INVOICE-116102025.pdf",                cid: "QmTi5kKc8t5cLfoQvDwnazcrE5HUwZgEe3pUWuCTwWmTt8", url: `${IPFS}/QmTi5kKc8t5cLfoQvDwnazcrE5HUwZgEe3pUWuCTwWmTt8` },
      { label: "T-1 Transit Doc",      name: "T-1_inv_116102025.pdf",               cid: "QmYphDBmY4nGx1o3vxNPLetSYL1CdzW6pHuaxZMCqGySb3", url: `${IPFS}/QmYphDBmY4nGx1o3vxNPLetSYL1CdzW6pHuaxZMCqGySb3` },
      { label: "Kernel Addendum",      name: "CONTRACT_11.06.2025_Kernel_391mt.pdf", cid: "QmPMAkPaVrfrXFpLrWQoUPP2rVdjgugMM99wJPkq5RQuBf", url: `${IPFS}/QmPMAkPaVrfrXFpLrWQoUPP2rVdjgugMM99wJPkq5RQuBf` },
    ],
    checkpoints: [
      { id: 1, status: "completed" as const, txHash: "0xcde001...", date: "2025-10-27" },
      { id: 2, status: "completed" as const, txHash: "0xcde002...", date: "2025-10-29" },
      { id: 3, status: "completed" as const, txHash: "0xcde003...", date: "2025-10-31" },
      { id: 4, status: "completed" as const, txHash: "0xcde004...", date: "2025-11-04" },
      { id: 5, status: "completed" as const, txHash: "0xcde005...", date: "2025-11-15" },
      { id: 6, status: "completed" as const, txHash: "0xcde006...", date: "2025-11-26" },
    ],
  },
  {
    id: "RWA-SX-004",
    contractRef: "IT-201125",
    name: "Striped Sunflower Seeds — 22 MT",
    type: "Trade Receivable",
    assetType: "trade_receivable" as const,
    commodity: "Striped Sunflower Seeds",
    volumeMT: 22,
    buyer: "OSKUTUOTE OY",
    buyerCountry: "Finland",
    intermediary: "CEREAL CROPS TRADING LLP",
    loanAmount: 16_500,
    contractValue: 22_000,
    currency: "USDC",
    tenor: "30 days",
    tenorDays: 30,
    aprMin: 6,
    aprMax: 8,
    ltv: 75,
    stage: "Repaid" as const,
    status: "matured" as const,
    tranche: "DROP",
    oracleCompleted: 6,
    oracleTotal: 6,
    counterparty: "FG GENIIVSKE",
    originator: "SX Capital",
    originationDate: "2025-11-20",
    maturityDate: "2025-12-20",
    metadataCid: "QmZwewf5XVCNGi3DCfsni37mv1c4PDEnRf48onYsSMJuCy",
    ipfsDocuments: [
      { label: "Contract",             name: "CONTRACT.pdf",                         cid: "QmeSGoFTqCUqnxGQuhk51YbedoYBRyxM7pjharEKSeECnb", url: `${IPFS}/QmeSGoFTqCUqnxGQuhk51YbedoYBRyxM7pjharEKSeECnb` },
      { label: "Declaration / CMR / EUR.1 / Phyto", name: "declaration_CMR_invoice_EUR1_Phyto.pdf", cid: "QmZc5CuuzNr569XeTyf4scZHrsL9CMuBKL5SH1BjGfMwdn", url: `${IPFS}/QmZc5CuuzNr569XeTyf4scZHrsL9CMuBKL5SH1BjGfMwdn` },
      { label: "Invoice",              name: "INVOICE-128112025.pdf",                cid: "QmU2kRnxtUx2WP2fcS9JhdAFrcAVEGTooTt8vp5orJHLUa", url: `${IPFS}/QmU2kRnxtUx2WP2fcS9JhdAFrcAVEGTooTt8vp5orJHLUa` },
      { label: "T-1 Transit Doc",      name: "T-1_inv_128112025.pdf",               cid: "QmVnCB268T34GiqrCJqHudF3gyKXd2q3fr4fJEyxAXqS83", url: `${IPFS}/QmVnCB268T34GiqrCJqHudF3gyKXd2q3fr4fJEyxAXqS83` },
    ],
    checkpoints: [
      { id: 1, status: "completed" as const, txHash: "0xdef001...", date: "2025-11-20" },
      { id: 2, status: "completed" as const, txHash: "0xdef002...", date: "2025-11-21" },
      { id: 3, status: "completed" as const, txHash: "0xdef003...", date: "2025-11-24" },
      { id: 4, status: "completed" as const, txHash: "0xdef004...", date: "2025-11-28" },
      { id: 5, status: "completed" as const, txHash: "0xdef005...", date: "2025-12-10" },
      { id: 6, status: "completed" as const, txHash: "0xdef006...", date: "2025-12-20" },
    ],
  },
  {
    id: "RWA-SX-005",
    contractRef: "IT-221125",
    name: "Sunflower Kernel (hulled) — 22.4 MT",
    type: "Trade Receivable",
    assetType: "trade_receivable" as const,
    commodity: "Sunflower Kernel (hulled)",
    volumeMT: 22.4,
    buyer: "OSKUTUOTE OY",
    buyerCountry: "Finland",
    intermediary: "CEREAL CROPS TRADING LLP",
    loanAmount: 22_400,
    contractValue: 29_866,
    currency: "USDC",
    tenor: "30 days",
    tenorDays: 30,
    aprMin: 6,
    aprMax: 8,
    ltv: 75,
    stage: "Repaid" as const,
    status: "matured" as const,
    tranche: "DROP",
    oracleCompleted: 6,
    oracleTotal: 6,
    counterparty: "FG GENIIVSKE",
    originator: "SX Capital",
    originationDate: "2025-11-22",
    maturityDate: "2025-12-22",
    metadataCid: "QmegjFuzV6uo7eQ27a1w92ufdc3hTDTdaqESAz2egsb1hq",
    ipfsDocuments: [
      { label: "Contract",             name: "CONTRACT.pdf",                        cid: "QmUJPQNQapNTBgArtZJnUg1JbZrxghPrVMGGriYmBCPKbs", url: `${IPFS}/QmUJPQNQapNTBgArtZJnUg1JbZrxghPrVMGGriYmBCPKbs` },
      { label: "Declaration / CMR / EUR.1 / Phyto", name: "declaration_CMR_invoice_EUR1_Phyto.pdf", cid: "QmPAHiSjVjxxGgp7oFLmDYgQU6nXxe38ytWEUn6uEpUHHZ", url: `${IPFS}/QmPAHiSjVjxxGgp7oFLmDYgQU6nXxe38ytWEUn6uEpUHHZ` },
      { label: "Invoice",              name: "INVOICE_9267.pdf",                    cid: "QmNifs7ZqnzpCFBsmQXtJRQhwkACE7gJ69FK2c8ar66ZAo", url: `${IPFS}/QmNifs7ZqnzpCFBsmQXtJRQhwkACE7gJ69FK2c8ar66ZAo` },
      { label: "T-1 Transit Doc",      name: "T-1_inv_9267.pdf",                   cid: "QmbzWt4jMS4gpC2N8Q7GkeigCXvsPhAyXa7e5srbau9AdW", url: `${IPFS}/QmbzWt4jMS4gpC2N8Q7GkeigCXvsPhAyXa7e5srbau9AdW` },
      { label: "Framework Contract",   name: "Contract_16092025.pdf",              cid: "QmdtVLv1r734yeZH5f3zzwB9WNUEhFSao7rbf22wc1suWN", url: `${IPFS}/QmdtVLv1r734yeZH5f3zzwB9WNUEhFSao7rbf22wc1suWN` },
    ],
    checkpoints: [
      { id: 1, status: "completed" as const, txHash: "0xefg001...", date: "2025-11-22" },
      { id: 2, status: "completed" as const, txHash: "0xefg002...", date: "2025-11-23" },
      { id: 3, status: "completed" as const, txHash: "0xefg003...", date: "2025-11-26" },
      { id: 4, status: "completed" as const, txHash: "0xefg004...", date: "2025-11-30" },
      { id: 5, status: "completed" as const, txHash: "0xefg005...", date: "2025-12-12" },
      { id: 6, status: "completed" as const, txHash: "0xefg006...", date: "2025-12-22" },
    ],
  },
  {
    id: "RWA-SX-006",
    contractRef: "IT-260126",
    name: "Striped Sunflower Seeds — 22 MT + Kernel 418 MT",
    type: "Trade Receivable",
    assetType: "trade_receivable" as const,
    commodity: "Striped Sunflower Seeds + Sunflower Kernel",
    volumeMT: 22,
    buyer: "OSKUTUOTE OY",
    buyerCountry: "Finland",
    intermediary: "CEREAL CROPS TRADING LLP",
    loanAmount: 16_500,
    contractValue: 22_000,
    currency: "USDC",
    tenor: "30 days",
    tenorDays: 30,
    aprMin: 6,
    aprMax: 8,
    ltv: 75,
    stage: "Repaid" as const,
    status: "matured" as const,
    tranche: "DROP",
    oracleCompleted: 6,
    oracleTotal: 6,
    counterparty: "FG GENIIVSKE",
    originator: "SX Capital",
    originationDate: "2026-01-26",
    maturityDate: "2026-02-25",
    metadataCid: "QmUrDDoNwyx5Jz3RLdBNnpFz8jxbniZb93h7vHZEJop6Q9",
    ipfsDocuments: [
      { label: "Contract",             name: "CONTRACT.pdf",                          cid: "QmUzRLQtTM7mgaUSbGCwJWZuxvkLepWrq21L3ar6Bqiiug", url: `${IPFS}/QmUzRLQtTM7mgaUSbGCwJWZuxvkLepWrq21L3ar6Bqiiug` },
      { label: "Declaration / CMR / EUR.1 / Phyto", name: "declaration_CMR_invoice_EUR1_Phyto.pdf", cid: "QmYhyDskwu1TqDeXfjyC7kfXVD2YLJnEbqay3VWwNFQijv", url: `${IPFS}/QmYhyDskwu1TqDeXfjyC7kfXVD2YLJnEbqay3VWwNFQijv` },
      { label: "Invoice",              name: "INVOICE-138012026.pdf",                 cid: "QmNq3ZAtr9JBsvyUzAEc87aCJbtv4gXGNXb1gBSpa6Q6E4", url: `${IPFS}/QmNq3ZAtr9JBsvyUzAEc87aCJbtv4gXGNXb1gBSpa6Q6E4` },
      { label: "T-1 Transit Doc",      name: "T-1_inv_138012026.pdf",                cid: "QmeAKgPvXsy5KFtQGFqemeJep1Wkv9xwkULAnsAjWYtudV", url: `${IPFS}/QmeAKgPvXsy5KFtQGFqemeJep1Wkv9xwkULAnsAjWYtudV` },
      { label: "Kernel Addendum",      name: "CONTRACT_10.06.2025_Kernel_418mt.pdf",  cid: "QmQ34xWj1HKaFRtpGDqogkKU3L2NKWRvNu5rPG3uQMSdUB", url: `${IPFS}/QmQ34xWj1HKaFRtpGDqogkKU3L2NKWRvNu5rPG3uQMSdUB` },
    ],
    checkpoints: [
      { id: 1, status: "completed" as const, txHash: "0xfgh001...", date: "2026-01-26" },
      { id: 2, status: "completed" as const, txHash: "0xfgh002...", date: "2026-01-28" },
      { id: 3, status: "completed" as const, txHash: "0xfgh003...", date: "2026-01-30" },
      { id: 4, status: "completed" as const, txHash: "0xfgh004...", date: "2026-02-03" },
      { id: 5, status: "completed" as const, txHash: "0xfgh005...", date: "2026-02-15" },
      { id: 6, status: "completed" as const, txHash: "0xfgh006...", date: "2026-02-25" },
    ],
  },
  {
    id: "RWA-SX-007",
    contractRef: "IT-090226",
    name: "Feed Corn — 21.1 MT",
    type: "Trade Receivable",
    assetType: "trade_receivable" as const,
    commodity: "Feed Corn",
    volumeMT: 21.1,
    buyer: "OSKUTUOTE OY",
    buyerCountry: "Finland",
    intermediary: "CEREAL CROPS TRADING LLP",
    loanAmount: 3_165,
    contractValue: 4_220,
    currency: "USDC",
    tenor: "30 days",
    tenorDays: 30,
    aprMin: 6,
    aprMax: 8,
    ltv: 75,
    stage: "Repaid" as const,
    status: "matured" as const,
    tranche: "DROP",
    oracleCompleted: 6,
    oracleTotal: 6,
    counterparty: "FG GENIIVSKE",
    originator: "SX Capital",
    originationDate: "2026-02-09",
    maturityDate: "2026-03-11",
    metadataCid: "QmchK6Qi6xJJ7VhNZWyY1ULkQS8NbXkU4KUboGceLNeHFu",
    ipfsDocuments: [
      { label: "Contract",             name: "CONTRACT.pdf",                         cid: "QmX9uuKpbgQaHgXqMiaiwCDFzD4xhTT1DvHd1ME8ejDLo7", url: `${IPFS}/QmX9uuKpbgQaHgXqMiaiwCDFzD4xhTT1DvHd1ME8ejDLo7` },
      { label: "Declaration / CMR / EUR.1 / Phyto", name: "declaration_CMR_invoice_EUR1_Phyto.pdf", cid: "QmPsfPZhV8HMqLJtBKSGa7UkQdPrSbqtE3A98wZSvXRGw3", url: `${IPFS}/QmPsfPZhV8HMqLJtBKSGa7UkQdPrSbqtE3A98wZSvXRGw3` },
      { label: "Invoice",              name: "INVOICE-139022026.pdf",                cid: "QmYNRRdc1t83QPZZyc51jvvPoCuW1aCDQ1nTmLL2usnjry", url: `${IPFS}/QmYNRRdc1t83QPZZyc51jvvPoCuW1aCDQ1nTmLL2usnjry` },
      { label: "T-1 Transit Doc",      name: "T-1_AC9282HE.pdf",                    cid: "QmZbgN7VKENBZ4jxfFFw8kiVNNqmvzUZfXkpz7vzum7WHp", url: `${IPFS}/QmZbgN7VKENBZ4jxfFFw8kiVNNqmvzUZfXkpz7vzum7WHp` },
    ],
    checkpoints: [
      { id: 1, status: "completed" as const, txHash: "0xghi001...", date: "2026-02-09" },
      { id: 2, status: "completed" as const, txHash: "0xghi002...", date: "2026-02-10" },
      { id: 3, status: "completed" as const, txHash: "0xghi003...", date: "2026-02-13" },
      { id: 4, status: "completed" as const, txHash: "0xghi004...", date: "2026-02-18" },
      { id: 5, status: "completed" as const, txHash: "0xghi005...", date: "2026-03-01" },
      { id: 6, status: "completed" as const, txHash: "0xghi006...", date: "2026-03-11" },
    ],
  },
  {
    id: "RWA-SX-008",
    contractRef: "IT-230426",
    name: "Feed Corn — 23 MT",
    type: "Trade Receivable",
    assetType: "trade_receivable" as const,
    commodity: "Feed Corn",
    volumeMT: 23,
    buyer: "OSKUTUOTE OY",
    buyerCountry: "Finland",
    intermediary: "CEREAL CROPS TRADING LLP",
    loanAmount: 3_450,
    contractValue: 4_600,
    currency: "USDC",
    tenor: "30 days",
    tenorDays: 30,
    aprMin: 6,
    aprMax: 8,
    ltv: 75,
    stage: "Active" as const,
    status: "active" as const,
    tranche: "DROP",
    oracleCompleted: 4,
    oracleTotal: 6,
    counterparty: "FG GENIIVSKE",
    originator: "SX Capital",
    originationDate: "2026-04-23",
    maturityDate: "2026-05-23",
    metadataCid: "QmV7TcWB2t9rQRCGrVvTYJcNGzhroTxrdNoMLVLyeceocX",
    ipfsDocuments: [
      { label: "Contract",             name: "CONTRACT.pdf",                          cid: "QmQuLCbz5ipPLRQRmBhgKa7T6ib133Zdv8M8zjRSkDnEvK", url: `${IPFS}/QmQuLCbz5ipPLRQRmBhgKa7T6ib133Zdv8M8zjRSkDnEvK` },
      { label: "Declaration / CMR / EUR.1 / Phyto", name: "declaration_CMR_invoice_EUR1_Phyto.pdf", cid: "QmSrCixsv8nRY1GTfbTVLdcuXpg2bTApRhEM5svox96iqi", url: `${IPFS}/QmSrCixsv8nRY1GTfbTVLdcuXpg2bTApRhEM5svox96iqi` },
      { label: "Invoice",              name: "INVOICE-140022026.pdf",                 cid: "Qma5eFcdcQTHoJLcZXJhiHxSfV6y1b3VrNCsRBu29ErGf9", url: `${IPFS}/Qma5eFcdcQTHoJLcZXJhiHxSfV6y1b3VrNCsRBu29ErGf9` },
      { label: "T-1 Transit Doc",      name: "T-1_inv_N140042026.pdf",               cid: "Qme5TvoaLaRV5nSHdGvQq7m9cxeWCyLLvqdaUwQR41VmjB", url: `${IPFS}/Qme5TvoaLaRV5nSHdGvQq7m9cxeWCyLLvqdaUwQR41VmjB` },
      { label: "Corn Framework",       name: "CONTRACT_27.03.2026_Corn_92MT.pdf",     cid: "QmaVSj4U8xT9YKHH4VYj7xM2STnNDFmcRN5CbHcYLf4cVt", url: `${IPFS}/QmaVSj4U8xT9YKHH4VYj7xM2STnNDFmcRN5CbHcYLf4cVt` },
    ],
    checkpoints: [
      { id: 1, status: "completed" as const, txHash: "0xhij001...", date: "2026-04-23" },
      { id: 2, status: "completed" as const, txHash: "0xhij002...", date: "2026-04-24" },
      { id: 3, status: "completed" as const, txHash: "0xhij003...", date: "2026-04-27" },
      { id: 4, status: "completed" as const, txHash: "0xhij004...", date: "2026-05-02" },
      { id: 5, status: "pending" as const,   txHash: null, date: null },
      { id: 6, status: "upcoming" as const,  txHash: null, date: null },
    ],
  },
  {
    id: "RWA-SX-009",
    contractRef: "IT-290426",
    name: "Striped Sunflower Seeds — 20.2 MT",
    type: "Trade Receivable",
    assetType: "trade_receivable" as const,
    commodity: "Striped Sunflower Seeds",
    volumeMT: 20.2,
    buyer: "OSKUTUOTE OY",
    buyerCountry: "Finland",
    intermediary: "CEREAL CROPS TRADING LLP",
    loanAmount: 15_150,
    contractValue: 20_200,
    currency: "USDC",
    tenor: "30 days",
    tenorDays: 30,
    aprMin: 6,
    aprMax: 8,
    ltv: 75,
    stage: "Active" as const,
    status: "active" as const,
    tranche: "DROP",
    oracleCompleted: 2,
    oracleTotal: 6,
    counterparty: "FG GENIIVSKE",
    originator: "SX Capital",
    originationDate: "2026-04-29",
    maturityDate: "2026-05-29",
    metadataCid: "QmRRDiY4S3u6aoZ2tLZkcnrnFhNM3a8QBhe7Crwo7Yn2Xk",
    ipfsDocuments: [
      { label: "Contract",             name: "CONTRACT.pdf",                         cid: "QmWbZxMdYLjWmQ5FPsRfocV5TZh1vYkrWXgt4eS6s1SDzU", url: `${IPFS}/QmWbZxMdYLjWmQ5FPsRfocV5TZh1vYkrWXgt4eS6s1SDzU` },
      { label: "Declaration / CMR / EUR.1 / Phyto", name: "declaration_CMR_invoice_EUR1_Phyto.pdf", cid: "QmWCuPC3Erh6nsN28wjbm64qCsVtKeHBYAV5z38x2jv7wF", url: `${IPFS}/QmWCuPC3Erh6nsN28wjbm64qCsVtKeHBYAV5z38x2jv7wF` },
      { label: "Invoice",              name: "INVOICE-141052026.pdf",                cid: "QmRcqdZLPPTKgpJQMGkhLFESQBAb2P6wigMdBwQ2VgvSa4", url: `${IPFS}/QmRcqdZLPPTKgpJQMGkhLFESQBAb2P6wigMdBwQ2VgvSa4` },
      { label: "T-1 Transit Doc",      name: "T-1_inv_141052026.pdf",               cid: "QmNcVA6tvV3rHA663wEvNmaNKYhVgNF2ELiKaeSJj3ZZzb", url: `${IPFS}/QmNcVA6tvV3rHA663wEvNmaNKYhVgNF2ELiKaeSJj3ZZzb` },
      { label: "Supplementary",        name: "Contract_28.04.2026_Stripped_22MT.pdf", cid: "QmP4iUMAqGox3JzYDHGUNuRxuhGg5haatqSg8XdyBY8thE", url: `${IPFS}/QmP4iUMAqGox3JzYDHGUNuRxuhGg5haatqSg8XdyBY8thE` },
    ],
    checkpoints: [
      { id: 1, status: "completed" as const, txHash: "0xijk001...", date: "2026-04-29" },
      { id: 2, status: "completed" as const, txHash: "0xijk002...", date: "2026-04-30" },
      { id: 3, status: "pending" as const,   txHash: null, date: null },
      { id: 4, status: "upcoming" as const,  txHash: null, date: null },
      { id: 5, status: "upcoming" as const,  txHash: null, date: null },
      { id: 6, status: "upcoming" as const,  txHash: null, date: null },
    ],
  },
  {
    id: "RWA-SX-010",
    contractRef: "IT-110526",
    name: "Feed Corn — 23 MT",
    type: "Trade Receivable",
    assetType: "trade_receivable" as const,
    commodity: "Feed Corn",
    volumeMT: 23,
    buyer: "OSKUTUOTE OY",
    buyerCountry: "Finland",
    intermediary: "CEREAL CROPS TRADING LLP",
    loanAmount: 3_450,
    contractValue: 4_600,
    currency: "USDC",
    tenor: "30 days",
    tenorDays: 30,
    aprMin: 6,
    aprMax: 8,
    ltv: 75,
    stage: "Active" as const,
    status: "active" as const,
    tranche: "DROP",
    oracleCompleted: 1,
    oracleTotal: 6,
    counterparty: "FG GENIIVSKE",
    originator: "SX Capital",
    originationDate: "2026-05-11",
    maturityDate: "2026-06-10",
    metadataCid: "QmVZoiCK6cNYxzsRcdUmkV1ASNyKw4hYZwnsy214cuDKZA",
    ipfsDocuments: [
      { label: "Contract",             name: "CONTRACT.pdf",                          cid: "QmdrkouUEafDRTBD8Ds8sSgih19MfpPaRaed2gRZWDxDY6", url: `${IPFS}/QmdrkouUEafDRTBD8Ds8sSgih19MfpPaRaed2gRZWDxDY6` },
      { label: "Declaration / CMR / EUR.1 / Phyto", name: "declaration_CMR_invoice_EUR1_Phyto.pdf", cid: "QmTiXwPeVr5qtLjqVB8EY37WTc45Lo3NTzf9KLqCpSLHiT", url: `${IPFS}/QmTiXwPeVr5qtLjqVB8EY37WTc45Lo3NTzf9KLqCpSLHiT` },
      { label: "Invoice",              name: "INVOICE-142052026.pdf",                 cid: "Qme3RSTFRsEUbfNmnhHWRpQjcQKGH8ZofiuwT2T4s53QDS", url: `${IPFS}/Qme3RSTFRsEUbfNmnhHWRpQjcQKGH8ZofiuwT2T4s53QDS` },
      { label: "T-1 Transit Doc",      name: "T-1_inv_142052026.pdf",                cid: "QmWrghx8moKtJWQ4pxqFuAfC6MUkTWiv2gZH9UZexDcVyK", url: `${IPFS}/QmWrghx8moKtJWQ4pxqFuAfC6MUkTWiv2gZH9UZexDcVyK` },
      { label: "Corn Framework",       name: "CONTRACT_27.03.2026_Corn_92MT.pdf",     cid: "QmW5Qh8nKkGTQCMMLs1UjLX1GuPNWSifxw6JgVNTk5qwkY", url: `${IPFS}/QmW5Qh8nKkGTQCMMLs1UjLX1GuPNWSifxw6JgVNTk5qwkY` },
    ],
    checkpoints: [
      { id: 1, status: "completed" as const, txHash: "0xjkl001...", date: "2026-05-11" },
      { id: 2, status: "pending" as const,   txHash: null, date: null },
      { id: 3, status: "upcoming" as const,  txHash: null, date: null },
      { id: 4, status: "upcoming" as const,  txHash: null, date: null },
      { id: 5, status: "upcoming" as const,  txHash: null, date: null },
      { id: 6, status: "upcoming" as const,  txHash: null, date: null },
    ],
  },
];

export const MULTIPLIER_PHASES = [
  { id: "pilot",   label: "Pilot",   quarter: "Now",     pools: 1,  tvlTarget: "$0.25M",  status: "active" as const },
  { id: "scale1",  label: "Scale 1", quarter: "Q4 2026", pools: 3,  tvlTarget: "$2M",     status: "upcoming" as const },
  { id: "scale2",  label: "Scale 2", quarter: "Q1 2027", pools: 8,  tvlTarget: "$10M",    status: "upcoming" as const },
  { id: "scale3",  label: "Scale 3", quarter: "Q2 2027", pools: 20, tvlTarget: "$50M+",   status: "upcoming" as const },
];

export const COMPLIANCE_CHECKLIST = [
  { id: 1, label: "KYC / AML",              status: "done" as const,    note: "Proton AG (Switzerland) — E2E-encrypted verification" },
  { id: 2, label: "GDPR",                   status: "done" as const,    note: "Data encrypted at-rest and in-transit" },
  { id: 3, label: "MiCA",                   status: "pending" as const, note: "Final legal opinion pending Q4 2026" },
  { id: 4, label: "Ukrainian Law",          status: "done" as const,    note: "FG Geniivske registered, export licenses current" },
  { id: 5, label: "UK Law (FSMA 2000)",     status: "done" as const,    note: "CCT LLP, Companies House № OC438291" },
  { id: 6, label: "Bankruptcy Remoteness", status: "done" as const,    note: "SPV ring-fenced via assignment agreement" },
  { id: 7, label: "Dispute Resolution",     status: "done" as const,    note: "ICC Arbitration, Paris. Governing law: England & Wales" },
  { id: 8, label: "Regulatory Reporting",  status: "done" as const,    note: "Chainlink PoR + quarterly investor reports" },
];

export const LEGAL_DOCUMENTS = [
  { id: "DOC-001", title: "Offering Memorandum v2.1",           category: "Memorandum",  date: "2026-01-15", version: "v2.1", status: "active", ipfs: "QmXm3..." },
  { id: "DOC-002", title: "Master Subscription Agreement",       category: "Agreement",   date: "2026-01-20", version: "v2.0", status: "active", ipfs: "QmYn4..." },
  { id: "DOC-003", title: "Smart Contract Audit — Certik",       category: "Audit",       date: "2026-02-10", version: "v1.0", status: "active", ipfs: "QmZo5..." },
  { id: "DOC-004", title: "KYC/AML Compliance Report",           category: "Compliance",  date: "2026-03-05", version: "v1.5", status: "active", ipfs: "QmAp6..." },
  { id: "DOC-005", title: "SPV Formation Documents (BVI)",       category: "Corporate",   date: "2025-11-30", version: "v1.0", status: "active", ipfs: "QmBq7..." },
  { id: "DOC-006", title: "DROP Token Term Sheet",               category: "Terms",       date: "2026-03-10", version: "v1.2", status: "active", ipfs: "QmCr8..." },
  { id: "DOC-007", title: "MEZZ Token Term Sheet",               category: "Terms",       date: "2026-03-10", version: "v1.2", status: "active", ipfs: "QmDs9..." },
  { id: "DOC-008", title: "Origination Partner Agreement — SX",  category: "Agreement",   date: "2026-04-01", version: "v1.0", status: "active", ipfs: "QmEt0..." },
];

export const TEAM_MEMBERS = [
  {
    id: "USR-01",
    name: "Андрей",
    nameEn: "Andrey",
    email: "andrey@trinityfund.io",
    role: "Originator / Strategist",
    bio: "Founder & Strategist. Agricultural trade origination, Polygon/Centrifuge architecture.",
    joinedAt: "2025-09-01",
    status: "active" as const,
    avatar: "АН",
    emoji: "👑",
    accentClass: "border-primary/30 bg-primary/5",
    avatarClass: "bg-primary/15 text-primary",
    permissions: ["Pool Admin", "Deal Create", "Oracle Submit", "Report View"],
  },
  {
    id: "USR-02",
    name: "Валя",
    nameEn: "Valya",
    email: "valya@trinityfund.io",
    role: "Financial Officer",
    bio: "Financial Director. Accounting, investor relations, tranche distributions.",
    joinedAt: "2025-10-01",
    status: "active" as const,
    avatar: "ВА",
    emoji: "💰",
    accentClass: "border-emerald-400/30 bg-emerald-400/5",
    avatarClass: "bg-emerald-400/15 text-emerald-400",
    permissions: ["Report View", "Accounting", "Investor Approve"],
  },
  {
    id: "USR-03",
    name: "Mira",
    nameEn: "Mira",
    email: "mira@trinityfund.io",
    role: "Coordinator",
    bio: "Operations Coordinator. Deal flow management, compliance tracking, counterparty relations.",
    joinedAt: "2025-11-01",
    status: "active" as const,
    avatar: "MI",
    emoji: "🔗",
    accentClass: "border-violet-400/30 bg-violet-400/5",
    avatarClass: "bg-violet-400/15 text-violet-400",
    permissions: ["Deal Create", "Oracle Submit", "Report View"],
  },
];

export const TBD_ROLES = [
  { role: "Legal Counsel",      icon: "⚖️", status: "Hiring",   note: "UK / EU crypto-asset law specialist" },
  { role: "Oracle Engineer",    icon: "🔗", status: "Hiring",   note: "Chainlink PoR integration, smart contracts" },
  { role: "Compliance Officer", icon: "🛡️", status: "Hiring",   note: "MiCA & GDPR ongoing compliance" },
  { role: "Community Manager",  icon: "🌐", status: "Hiring",   note: "Investor comms, Discord, social" },
];

export const MOCK_HOLDINGS = [
  { investor: "Family Office A",  tranche: "DROP", amount: 50_000,  tokens: 50_000,  yieldEarned: 1_166,  status: "active" },
  { investor: "DAO Treasury B",   tranche: "DROP", amount: 75_000,  tokens: 75_000,  yieldEarned: 1_750,  status: "active" },
  { investor: "HNWI C",           tranche: "MEZZ", amount: 26_250,  tokens: 26_250,  yieldEarned: 875,    status: "active" },
  { investor: "Angel Investor D", tranche: "TIN",  amount: 26_250,  tokens: 26_250,  yieldEarned: 1_313,  status: "active" },
  { investor: "Syndicate E",      tranche: "TIN",  amount: 26_250,  tokens: 26_250,  yieldEarned: 1_313,  status: "active" },
];
